-- Kcal-pal initial schema (single-user PWA).
-- Idempotent: safe to re-run from any partial state.
-- Every table uses RLS with policy auth.uid() = user_id.

-- Profile (single row, holds settings + targets)
create table if not exists profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  daily_calorie_target int default 2000,
  daily_protein_target_g int default 130,
  daily_carb_target_g int default 220,
  daily_fat_target_g int default 70,
  daily_fiber_target_g int default 30,
  height_in numeric,
  goal text default 'maintenance',
  created_at timestamptz default now()
);

-- Food log entries
create table if not exists food_entries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  consumed_at timestamptz not null default now(),
  meal text check (meal in ('breakfast','lunch','dinner','snack')),
  description text not null,
  source text check (source in ('text','photo','barcode')) not null,
  photo_url text,
  barcode text,
  calories numeric,
  protein_g numeric,
  carbs_g numeric,
  fat_g numeric,
  fiber_g numeric,
  serving_size text,
  raw_ai_response jsonb,
  edited_by_user boolean default false,
  created_at timestamptz default now()
);
create index if not exists food_entries_user_consumed_idx
  on food_entries (user_id, consumed_at desc);

-- Body weight (lbs)
create table if not exists body_weights (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  weight_lbs numeric not null,
  measured_at timestamptz not null default now(),
  source text default 'manual'
);
create index if not exists body_weights_user_measured_idx
  on body_weights (user_id, measured_at desc);

-- Oura daily summary
create table if not exists oura_daily (
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  sleep_score int,
  total_sleep_min int,
  rem_sleep_min int,
  deep_sleep_min int,
  hrv_avg numeric,
  resting_hr int,
  readiness_score int,
  activity_score int,
  steps int,
  temp_deviation numeric,
  raw jsonb,
  primary key (user_id, date)
);

-- Eight Sleep daily summary
create table if not exists eight_sleep_daily (
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  sleep_score int,
  total_sleep_min int,
  hrv_avg numeric,
  resting_hr int,
  bed_temp_avg_f numeric,
  toss_turns int,
  raw jsonb,
  primary key (user_id, date)
);

-- Cycle tracking (manual entry)
create table if not exists cycle_days (
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  cycle_day int,
  phase text check (phase in ('menstrual','follicular','ovulatory','luteal')),
  notes text,
  primary key (user_id, date)
);

-- Apple Health imports (one row per quarterly import file)
create table if not exists apple_health_imports (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  imported_at timestamptz default now(),
  date_range_start date,
  date_range_end date,
  records_imported int,
  file_name text
);

-- Apple Health datapoints (long format, one row per metric reading)
create table if not exists apple_health_data (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  metric text not null,
  value numeric not null,
  unit text,
  recorded_at timestamptz not null,
  source text
);
create index if not exists apple_health_data_user_metric_idx
  on apple_health_data (user_id, metric, recorded_at desc);
create unique index if not exists apple_health_data_unique
  on apple_health_data (user_id, metric, recorded_at);

-- Web push subscriptions
create table if not exists push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  created_at timestamptz default now()
);

-- Storage bucket for food photos: private, owner-only.
insert into storage.buckets (id, name, public)
values ('food-photos', 'food-photos', false)
on conflict (id) do nothing;

-- Enable RLS on every app table (no-op if already enabled).
alter table profiles enable row level security;
alter table food_entries enable row level security;
alter table body_weights enable row level security;
alter table oura_daily enable row level security;
alter table eight_sleep_daily enable row level security;
alter table cycle_days enable row level security;
alter table apple_health_imports enable row level security;
alter table apple_health_data enable row level security;
alter table push_subscriptions enable row level security;

-- Single-user policy: users can only see/touch their own rows.
-- drop-then-create so a partial previous run can't block us.
do $$
declare
  t text;
begin
  for t in
    select unnest(array[
      'profiles', 'food_entries', 'body_weights', 'oura_daily',
      'eight_sleep_daily', 'cycle_days', 'apple_health_imports',
      'apple_health_data', 'push_subscriptions'
    ])
  loop
    execute format('drop policy if exists %I on %I;', t || '_select', t);
    execute format(
      'create policy %I on %I for select using (auth.uid() = user_id);',
      t || '_select', t
    );
    execute format('drop policy if exists %I on %I;', t || '_insert', t);
    execute format(
      'create policy %I on %I for insert with check (auth.uid() = user_id);',
      t || '_insert', t
    );
    execute format('drop policy if exists %I on %I;', t || '_update', t);
    execute format(
      'create policy %I on %I for update using (auth.uid() = user_id) with check (auth.uid() = user_id);',
      t || '_update', t
    );
    execute format('drop policy if exists %I on %I;', t || '_delete', t);
    execute format(
      'create policy %I on %I for delete using (auth.uid() = user_id);',
      t || '_delete', t
    );
  end loop;
end $$;

-- Storage policies for food-photos bucket: owner-only.
drop policy if exists food_photos_select on storage.objects;
create policy food_photos_select
  on storage.objects for select
  using (bucket_id = 'food-photos' and auth.uid() = owner);
drop policy if exists food_photos_insert on storage.objects;
create policy food_photos_insert
  on storage.objects for insert
  with check (bucket_id = 'food-photos' and auth.uid() = owner);
drop policy if exists food_photos_update on storage.objects;
create policy food_photos_update
  on storage.objects for update
  using (bucket_id = 'food-photos' and auth.uid() = owner);
drop policy if exists food_photos_delete on storage.objects;
create policy food_photos_delete
  on storage.objects for delete
  using (bucket_id = 'food-photos' and auth.uid() = owner);

-- Auto-create a profile row on signup.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (user_id) values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Backfill: if you already signed in before the trigger existed, create
-- profile rows for any existing auth users (no-op for new projects).
insert into public.profiles (user_id)
select id from auth.users
on conflict (user_id) do nothing;
