"use client";

import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Printer, Mail } from "lucide-react";
import type { CycleAggregate } from "@/lib/cycles";

export type RecapSummary = {
  rangeStart: string;
  rangeEnd: string;
  daysLogged: number;
  food: {
    avgCalories: number | null;
    avgProtein: number | null;
    avgCarbs: number | null;
    avgFat: number | null;
    avgFiber: number | null;
  };
  recovery: {
    avgSleep: number | null;
    avgHrv: number | null;
    avgReadiness: number | null;
    avgRestingHr: number | null;
    avgTotalSleepMin: number | null;
    avgDailyBurn: number | null;
  };
  hydration: {
    avgMl: number | null;
    daysLogged: number;
    targetMl: number;
  };
  weight: {
    start: number | null;
    end: number | null;
    deltaLbs: number | null;
  };
  cycles: {
    count: number;
    avgLength: number | null;
    shortest: number | null;
    longest: number | null;
    latest: CycleAggregate | null;
    previous: CycleAggregate | null;
  };
  profile: {
    first_name: string | null;
    goal: string | null;
    activity_level: string | null;
    track_cycle: boolean;
  };
};

function fmt(n: number | null, digits = 0, unit = ""): string {
  if (n == null || !Number.isFinite(n)) return "—";
  return `${n.toFixed(digits)}${unit}`;
}

function fmtDate(iso: string): string {
  return new Date(`${iso}T00:00:00Z`).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  });
}

function ozFromMl(ml: number | null): string {
  if (ml == null) return "—";
  return `${Math.round(ml / 29.5735)} oz`;
}

function hrFromMin(m: number | null): string {
  if (m == null) return "—";
  const h = Math.floor(m / 60);
  const mm = Math.round(m % 60);
  return `${h}h ${mm}m`;
}

// Build a plain-text version of the recap for mailto: body.
function buildEmailText(s: RecapSummary): string {
  const lines: string[] = [];
  lines.push(`kcal pal 90-day recap`);
  lines.push(`${fmtDate(s.rangeStart)} – ${fmtDate(s.rangeEnd)}`);
  lines.push("");
  lines.push(`Food (avg of ${s.daysLogged} logged days)`);
  lines.push(`  Calories: ${fmt(s.food.avgCalories, 0, " kcal")}`);
  lines.push(`  Protein:  ${fmt(s.food.avgProtein, 0, " g")}`);
  lines.push(`  Carbs:    ${fmt(s.food.avgCarbs, 0, " g")}`);
  lines.push(`  Fat:      ${fmt(s.food.avgFat, 0, " g")}`);
  lines.push(`  Fiber:    ${fmt(s.food.avgFiber, 0, " g")}`);
  lines.push("");
  lines.push(`Recovery`);
  lines.push(`  Sleep score:    ${fmt(s.recovery.avgSleep)}`);
  lines.push(`  Total sleep:    ${hrFromMin(s.recovery.avgTotalSleepMin)}`);
  lines.push(`  HRV:            ${fmt(s.recovery.avgHrv, 1, " ms")}`);
  lines.push(`  Readiness:      ${fmt(s.recovery.avgReadiness)}`);
  lines.push(`  Resting HR:     ${fmt(s.recovery.avgRestingHr, 0, " bpm")}`);
  lines.push(`  Daily burn:     ${fmt(s.recovery.avgDailyBurn, 0, " kcal")}`);
  lines.push("");
  lines.push(`Hydration`);
  lines.push(`  Daily avg:      ${ozFromMl(s.hydration.avgMl)}`);
  lines.push(`  Target:         ${ozFromMl(s.hydration.targetMl)}`);
  lines.push(`  Days logged:    ${s.hydration.daysLogged}`);
  lines.push("");
  lines.push(`Weight`);
  if (s.weight.start != null && s.weight.end != null) {
    const dir = (s.weight.deltaLbs ?? 0) >= 0 ? "+" : "";
    lines.push(`  Start:   ${s.weight.start.toFixed(1)} lb`);
    lines.push(`  Current: ${s.weight.end.toFixed(1)} lb`);
    lines.push(`  Change:  ${dir}${(s.weight.deltaLbs ?? 0).toFixed(1)} lb`);
  } else {
    lines.push(`  No weight data in window`);
  }
  lines.push("");
  if (s.profile.track_cycle) {
    lines.push(`Cycles`);
    lines.push(`  Completed cycles in window: ${s.cycles.count}`);
    if (s.cycles.avgLength != null) {
      lines.push(`  Average length: ${s.cycles.avgLength.toFixed(1)} days`);
      lines.push(
        `  Range: ${s.cycles.shortest}–${s.cycles.longest} days`,
      );
    }
    if (s.cycles.latest && s.cycles.previous) {
      const c = s.cycles.latest;
      const p = s.cycles.previous;
      lines.push("");
      lines.push(`  Latest cycle vs previous:`);
      lines.push(
        `    Readiness: ${fmt(c.avgReadiness)} vs ${fmt(p.avgReadiness)}`,
      );
      lines.push(
        `    Sleep:     ${fmt(c.avgSleep)} vs ${fmt(p.avgSleep)}`,
      );
      lines.push(
        `    HRV:       ${fmt(c.avgHrv, 1, " ms")} vs ${fmt(p.avgHrv, 1, " ms")}`,
      );
    }
  }
  lines.push("");
  lines.push(`Generated by kcal pal.`);
  return lines.join("\n");
}

function Stat({
  label,
  value,
  hint,
}: {
  label: string;
  value: string;
  hint?: string;
}) {
  return (
    <div className="space-y-0.5">
      <p className="text-xs uppercase tracking-wider text-muted-foreground">
        {label}
      </p>
      <p className="font-serif text-xl tabular-nums">{value}</p>
      {hint ? <p className="text-xs text-muted-foreground">{hint}</p> : null}
    </div>
  );
}

export function RecapView({ summary: s }: { summary: RecapSummary }) {
  const ozAvg = ozFromMl(s.hydration.avgMl);
  const ozTarget = ozFromMl(s.hydration.targetMl);
  const greeting = s.profile.first_name
    ? `${s.profile.first_name}'s 90-day picture`
    : "Your 90-day picture";

  const emailHref = `mailto:?subject=${encodeURIComponent(
    "My kcal pal 90-day recap",
  )}&body=${encodeURIComponent(buildEmailText(s))}`;

  return (
    <div className="space-y-4">
      <div className="flex justify-end gap-2 print:hidden">
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() => window.print()}
        >
          <Printer className="size-4" />
          <span className="ml-1">Save as PDF</span>
        </Button>
        <Button type="button" variant="outline" size="sm" asChild>
          <a href={emailHref}>
            <Mail className="size-4" />
            <span className="ml-1">Email it</span>
          </a>
        </Button>
      </div>

      <Card className="print:border-none print:shadow-none">
        <CardContent className="space-y-6 pt-6">
          <header className="space-y-1 border-b pb-4">
            <h2 className="font-serif text-3xl font-medium">{greeting}</h2>
            <p className="text-sm text-muted-foreground">
              {fmtDate(s.rangeStart)} – {fmtDate(s.rangeEnd)}
            </p>
            {s.profile.goal ? (
              <p className="text-xs uppercase tracking-wider text-muted-foreground">
                Goal: {s.profile.goal} · {s.profile.activity_level ?? "—"}
              </p>
            ) : null}
          </header>

          <section className="space-y-3">
            <h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
              Food (avg of {s.daysLogged} logged days)
            </h3>
            <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
              <Stat
                label="Calories"
                value={fmt(s.food.avgCalories, 0)}
                hint="kcal/day"
              />
              <Stat
                label="Protein"
                value={fmt(s.food.avgProtein, 0)}
                hint="g/day"
              />
              <Stat label="Carbs" value={fmt(s.food.avgCarbs, 0)} hint="g/day" />
              <Stat label="Fat" value={fmt(s.food.avgFat, 0)} hint="g/day" />
              <Stat
                label="Fiber"
                value={fmt(s.food.avgFiber, 0)}
                hint="g/day"
              />
            </div>
          </section>

          <section className="space-y-3">
            <h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
              Recovery (Oura)
            </h3>
            <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
              <Stat label="Sleep score" value={fmt(s.recovery.avgSleep, 0)} />
              <Stat
                label="Total sleep"
                value={hrFromMin(s.recovery.avgTotalSleepMin)}
              />
              <Stat
                label="HRV"
                value={fmt(s.recovery.avgHrv, 1)}
                hint="ms"
              />
              <Stat
                label="Readiness"
                value={fmt(s.recovery.avgReadiness, 0)}
              />
              <Stat
                label="Resting HR"
                value={fmt(s.recovery.avgRestingHr, 0)}
                hint="bpm"
              />
              <Stat
                label="Daily burn"
                value={fmt(s.recovery.avgDailyBurn, 0)}
                hint="kcal"
              />
            </div>
          </section>

          <section className="space-y-3">
            <h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
              Hydration
            </h3>
            <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
              <Stat
                label="Daily average"
                value={ozAvg}
                hint={`target ${ozTarget}`}
              />
              <Stat label="Days logged" value={String(s.hydration.daysLogged)} />
            </div>
          </section>

          <section className="space-y-3">
            <h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
              Weight
            </h3>
            {s.weight.start != null && s.weight.end != null ? (
              <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
                <Stat
                  label="Start"
                  value={`${s.weight.start.toFixed(1)} lb`}
                />
                <Stat
                  label="Current"
                  value={`${s.weight.end.toFixed(1)} lb`}
                />
                <Stat
                  label="Change"
                  value={`${(s.weight.deltaLbs ?? 0) >= 0 ? "+" : ""}${(s.weight.deltaLbs ?? 0).toFixed(1)} lb`}
                />
              </div>
            ) : (
              <p className="text-sm text-muted-foreground">
                No weight readings in this window.
              </p>
            )}
          </section>

          {s.profile.track_cycle ? (
            <section className="space-y-3">
              <h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Cycles
              </h3>
              <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
                <Stat label="Completed" value={String(s.cycles.count)} />
                <Stat
                  label="Avg length"
                  value={fmt(s.cycles.avgLength, 1)}
                  hint="days"
                />
                <Stat
                  label="Range"
                  value={
                    s.cycles.shortest != null && s.cycles.longest != null
                      ? `${s.cycles.shortest}–${s.cycles.longest}`
                      : "—"
                  }
                  hint="days"
                />
              </div>

              {s.cycles.latest && s.cycles.previous ? (
                <div className="rounded-lg border p-3 text-sm">
                  <p className="mb-2 text-xs uppercase tracking-wider text-muted-foreground">
                    Latest cycle vs previous
                  </p>
                  <table className="w-full tabular-nums">
                    <tbody>
                      <tr>
                        <td className="text-muted-foreground">Readiness</td>
                        <td className="text-right">
                          {fmt(s.cycles.latest.avgReadiness, 0)}
                        </td>
                        <td className="pl-3 text-right text-muted-foreground">
                          (was {fmt(s.cycles.previous.avgReadiness, 0)})
                        </td>
                      </tr>
                      <tr>
                        <td className="text-muted-foreground">Sleep</td>
                        <td className="text-right">
                          {fmt(s.cycles.latest.avgSleep, 0)}
                        </td>
                        <td className="pl-3 text-right text-muted-foreground">
                          (was {fmt(s.cycles.previous.avgSleep, 0)})
                        </td>
                      </tr>
                      <tr>
                        <td className="text-muted-foreground">HRV</td>
                        <td className="text-right">
                          {fmt(s.cycles.latest.avgHrv, 1)} ms
                        </td>
                        <td className="pl-3 text-right text-muted-foreground">
                          (was {fmt(s.cycles.previous.avgHrv, 1)} ms)
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              ) : null}
            </section>
          ) : null}

          <footer className="border-t pt-3 text-xs text-muted-foreground">
            Generated by kcal pal. Estimates are based on logged food entries
            and synced device data; not medical advice.
          </footer>
        </CardContent>
      </Card>
    </div>
  );
}
